import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        tertiary: "#825100",
        "surface-tint": "#494bd6",
        "on-tertiary-container": "#fffbff",
        "on-surface-variant": "#464554",
        "secondary-fixed-dim": "#4edea3",
        "surface-container-high": "#e9e6f3",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "outline-variant": "#c7c4d7",
        "surface-variant": "#e4e1ed",
        "tertiary-fixed": "#ffddb8",
        "secondary-container": "#6cf8bb",
        "inverse-primary": "#c0c1ff",
        "primary-fixed": "#e1e0ff",
        "on-surface": "#1b1b23",
        "surface-container": "#efecf8",
        "primary-container": "#6063ee",
        outline: "#767586",
        "tertiary-container": "#a36700",
        "on-primary-fixed-variant": "#2f2ebe",
        "secondary-fixed": "#6ffbbe",
        "on-secondary-container": "#00714d",
        background: "#fcf8ff",
        "on-primary-container": "#fffbff",
        "primary-fixed-dim": "#c0c1ff",
        "tertiary-fixed-dim": "#ffb95f",
        "inverse-surface": "#303038",
        "on-secondary-fixed": "#002113",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "on-background": "#1b1b23",
        "surface-bright": "#fcf8ff",
        "inverse-on-surface": "#f2effb",
        "on-tertiary-fixed": "#2a1700",
        primary: "#4648d4",
        secondary: "#006c49",
        "surface-container-highest": "#e4e1ed",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-fixed": "#07006c",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f5f2fe",
        error: "#ba1a1a",
        surface: "#fcf8ff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-dim": "#dbd8e4",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        xl: "32px",
        sm: "12px",
        xs: "8px",
        "2xl": "48px",
        lg: "24px",
        md: "16px",
        "container-max": "1280px",
        gutter: "24px",
      },
      fontFamily: {
        "headline-lg-mobile": ["var(--font-manrope)", "sans-serif"],
        "mono-stats": ["var(--font-inter)", "sans-serif"],
        "body-sm": ["var(--font-inter)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "headline-md": ["var(--font-manrope)", "sans-serif"],
        "headline-sm": ["var(--font-manrope)", "sans-serif"],
        "headline-lg": ["var(--font-manrope)", "sans-serif"],
        "display-lg": ["var(--font-manrope)", "sans-serif"],
        "label-md": ["var(--font-inter)", "sans-serif"],
        "label-sm": ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "mono-stats": ["20px", { lineHeight: "24px", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};

export default config;
